package_update: true
package_upgrade: true
packages:
  # Required by WASI SDK
  - cmake
  - ninja-build
  - make
  - autoconf
  - autogen
  - automake
  - libtool
  # Required by WASI SDK build script below
  - curl
  - jq
  - ca-certificates
  - wget
  - xz-utils
  # Required by WABT build script below
  - git
  - clang
  - lld
  - llvm-dev
  # Required by Emscripten SDK for building it
  - binutils
  - build-essential
  - file
  - python3
  - python3-pip
  # Required by Emscripten SDK for running it
  - libxml2
  - zip
  - unzip
  - git-lfs
  - ant
  - libidn12
  - openjdk-11-jre-headless
write_files:
  - path: /etc/cloud/metadata.repo
    content: wasm-fanclub/sdk
  - path: /etc/cloud/metadata.ref
    content: main
  - path: /opt/init/init.sh
    content: |
      #!/bin/bash
      read -r UPSTREAM_REF < /etc/cloud/metadata.ref
      read -r UPSTREAM_REPO < /etc/cloud/metadata.repo

      SCRIPTS=(
        "env-profile.sh"
        "tags.env"
        "build-wasi-profile.sh"
        "build-emcc-profile.sh"
        "build-wasmtime-profile.sh"
        "build-wabt-profile.sh"
        "install-wasi-sdk.sh"
        "install-emcc-sdk.sh"
        "install-wasmtime.sh"
        "install-wabt.sh"
        "build-sdk-check.sh"
      )

      BASE_URL="https://raw.githubusercontent.com/$UPSTREAM_REPO/$UPSTREAM_REF/init"

      mkdir -p /opt/init

      for script in "${SCRIPTS[@]}"; do
        TARGET="/opt/init/$script"

        if [[ ! -f "$TARGET" ]]; then
          echo "Fetching $script from $BASE_URL..."
          curl -fsSL "$BASE_URL/$script" -o "$TARGET"
        else
          echo "Using local $TARGET"
        fi

        if [[ "$script" != "env-profile.sh" && "$script" != "tags.env" ]]; then
          echo "Executing $TARGET"
          bash "$TARGET"
        fi
      done

      echo "source /opt/init/tags.env" >> /etc/profile.d/000-tags.env.sh
      bash /etc/profile.d/zzz-sdk-check.sh
runcmd:
  # Handle 'ssh-client' installation separately to avoid cloud-init apt issues
  - apt install -y ssh-client
  - bash /opt/init/init.sh
  - |-
    apt-get -y clean
    apt-get -y autoclean
    apt-get -y autoremove
    rm -rf /var/lib/apt/lists/*
    rm -rf /var/cache/debconf/*-old
    rm -rf /usr/share/doc/*
    rm -rf /usr/share/man/??
    rm -rf /usr/share/man/??_*
