name: Dump Test

on:
  workflow_dispatch:

jobs:
  dump-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/sdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run dump test
        run: |
          export DUMP_ROOT=${{ github.workspace }}/test
          bash dump-test.sh