name: Pin and Optimize Cloud-Init

on:
  workflow_dispatch:
    inputs:
      metadata_tag:
        description: 'Release tag to pin'
        required: true

env:
  METADATA_TAG: ${{ github.event.inputs.metadata_tag }}

permissions:
  contents: write

jobs:
  pin-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Install yq
        run: |
          VERSION=v4.48.1
          PLATFORM=linux_amd64

          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/yq_${PLATFORM} -O /usr/local/bin/yq &&\
          chmod +x /usr/local/bin/yq
      - name: Bump Cloud-Init Tag
        run: |
          yq -i '(.write_files[] | select(.path == "/etc/cloud/metadata.tag")).content = strenv(METADATA_TAG)' multipass/cloud-init.yml
      - name: Commit and Push changes
        run: |
          git add multipass/cloud-init.yml
          git commit -m "Pin cloud-init metadata tag to ${METADATA_TAG}" || echo "No changes to commit"
          git push origin main || true
      - name: Optimize /opt/init Scripts
        run: |
          SCRIPT_CONTENT=$(yq -r '.write_files[] | select(.path == "/opt/init/init.sh").content' multipass/cloud-init.yml)
          TARGET_BLOCK=$(awk '/^ *SCRIPTS=\(/,/^\)/ { print }' <<< "$SCRIPT_CONTENT")

          eval "$TARGET_BLOCK"

          for script in "${SCRIPTS[@]}"; do
            SRC_FILE="./init/$script"

            sed -i 's/\r$//' "$SRC_FILE"

            yq -i \
              ".write_files += [{
                \"path\": \"/opt/init/$script\",
                \"content\": load_str(\"$SRC_FILE\")
              }]" multipass/cloud-init.yml
            yq -i \
              "(.write_files[] | select(.path == \"/opt/init/$script\") | .content) style=\"literal\"" multipass/cloud-init.yml
          done
      - name: Force point tag to a headless commit
        run: |
          git checkout --detach
          git add multipass/cloud-init.yml
          git commit -m "Optimize /opt/init scripts and pin metadata tag to ${METADATA_TAG}"
          git tag -f ${METADATA_TAG}
          git push origin -f ${METADATA_TAG}