name: Publish SDK
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: read
  packages: write
  actions: write
env:
  IMAGE_NAME: sdk
jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get Build Arguments
        run: |
          BUILD_ARGS=$(cat ./init/tags.env)
          echo "BUILD_ARGS<<EOF" >> $GITHUB_ENV
          echo "$BUILD_ARGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Build intermediate image
        uses: docker/build-push-action@v6
        with:
          push: false
          file: docker/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:intermediate
          build-args: ${{ env.BUILD_ARGS }}
          load: true
      - name: Get PATH from intermediate image
        id: get-path
        run: |
          LAST_LINE=$(docker run --rm ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:intermediate "source /etc/profile.d/init/all.sh && printenv PATH" | tail -n 1)
          echo "AGGREGATED_PATH=$LAST_LINE" >> $GITHUB_ENV
      - name: Inject new PATH
        run: |
          sed -i "/^ENTRYPOINT/i ENV PATH=${{ env.AGGREGATED_PATH }}" docker/Dockerfile
      - name: Set Image Tags
        run: |
          echo "IMAGE_TAGS<<EOF" >> $GITHUB_ENV
          echo "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name || 'test-ignore' }}" >> $GITHUB_ENV
          if [ "${{ github.event.release.tag_name }}" != "" ]; then
            echo "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
          fi
          echo "EOF" >> $GITHUB_ENV
      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: |
            ${{ env.IMAGE_TAGS }}
          build-args: |
            ${{ env.BUILD_ARGS }}
      - name: Dump-test Latest Image
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run dump-test.yml --ref=${{ github.event.release.tag_name || github.ref_name }} --field tag=${{ github.event.release.tag_name || 'test-ignore' }}
      - name: Pin and Optimize Cloud-Init
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run pin-tag.yml --ref=${{ github.event.release.tag_name || github.ref_name }} \
            --field metadata_ref=${{ github.event.release.tag_name || github.ref_name }} \
            --field path=${{ env.AGGREGATED_PATH }} \
            --field publish=${{ github.event.release.tag_name != '' && 'true' || 'false' }}
